---
- hosts: production-servers
  vars:
    prefix: "{{ inventory_hostname }}_{{ansible_date_time.date}}"
    dir: "/etc"
    backup_dir: "/tmp"
    ftp_host: "{{services.vmx1.ftp.ftp_host}}"
    ftp_user: "{{services.vmx1.ftp.ftp_user}}"
    ftp_pass: "{{services.vmx1.ftp.ftp_pass}}"
    ftp_conf_dir: "{{services.vmx1.ftp.ftp_conf_dir}}"

  tasks:
    - name: Backup /etc folder
      archive:
        path: "{{dir}}"
        dest: "{{backup_dir}}/conf_{{prefix}}.tar.gz"
        format: gz
      become: yes

    - name: Upload file to FTP server
      shell: curl -T "{{backup_dir}}/conf_{{prefix}}.tar.gz" ftp://"{{ftp_user}}":"{{ftp_pass}}"@"{{ftp_host}}"/"{{ftp_conf_dir}}"/
    
    - name: Delete backup file on remote
      file:
        path: "{{backup_dir}}/conf_{{prefix}}.tar.gz"
        state: absent
      become: yes


- hosts: firewall-servers
  vars:
    prefix: "{{ inventory_hostname }}_{{ansible_date_time.date}}"
    backup_dir: "/tmp"
    ftp_host: "{{services.vmx1.ftp.ftp_host}}"
    ftp_user: "{{services.vmx1.ftp.ftp_user}}"
    ftp_pass: "{{services.vmx1.ftp.ftp_pass}}"
    ftp_conf_dir: "{{services.vmx1.ftp.ftp_conf_dir}}"
  tasks:
    - name: Backup /etc folder
      archive:
        path: 
          - "/etc"
          - "/usr/local/etc"
        dest: "{{backup_dir}}/conf_{{prefix}}.tar.gz"
        format: gz
      become: yes

    - name: Upload file to FTP server
      shell: curl -T "{{backup_dir}}/conf_{{prefix}}.tar.gz" ftp://"{{ftp_user}}":"{{ftp_pass}}"@"{{ftp_host}}"/"{{ftp_conf_dir}}"/
    
    - name: Delete backup file on remote
      file:
        path: "{{backup_dir}}/conf_{{prefix}}.tar.gz"
        state: absent
      become: yes


