---
- hosts: vmx1
  vars:
    container_name: 'rabbitmq'
  tasks:
    - name: Check existings of old RabbitMQ container
      docker_container_info:
        name: "{{ container_name }}"
      become: yes
      register: result

    - name: Stop old RabbitMQ container
      docker_container:
        name: "{{ container_name }}"
        state: stopped
        force_kill: yes
      become: yes
      when: result.exists

    - name: Remove old RabbitMQ container
      docker_container:
        name: "{{ container_name }}"
        state: absent
      become: yes
      when: result.exists

    - name: Make RabbitMQ container
      docker_container:
        name: "{{container_name}}"
        image: 'rabbitmq:3-management'
        ports:
          - '15672:15672'
          - '5672:5672'
        env:
          RABBITMQ_DEFAULT_USER: "TZBgaW3bDtYXRno5"
          RABBITMQ_DEFAULT_PASS: "N0uArziqiLWTsfsn"
      become: yes