---
- hosts: vmx1
  tasks:
    - name: Make GiTea container
      docker_container:
        name: gitea
        image: gitea/gitea:1.8.3
        ports:
          - "3001:3000"
        volumes:
          - '/mnt/backup/git:/data'
      become: yes
