---
- hosts: vmx1
  tasks:
    - name: Make Postgres10 container
      docker_container:
        name: redmine_db
        image: postgres:10
        network_mode: bridge
        volumes:
          - '/home/docker/redmine/pg_data:/var/lib/postgresql/data'
        env:
          POSTGRES_USER: "redmine"
          POSTGRES_PASSWORD: "OvGS6fz57eSGA2avO"
          POSTGRES_DB: "redmine"
      become: yes

    - name: Make Redmine container
      docker_container:
        name: redmine_server
        image: redmine
        hostname: "redmine.smedk.ru"
        links:
          - "redmine_db"
        ports:
          - "3000:3000"
        volumes:
          - '/home/docker/redmine/files:/usr/src/redmine/files'
        env:
          REDMINE_DB_POSTGRES: "redmine_db"
          REDMINE_DB_PORT: 5432
          REDMINE_DB_USERNAME: "redmine"
          REDMINE_DB_PASSWORD: "OvGS6fz57eSGA2avO"
          REDMINE_DB_DATABASE: "redmine"
      become: yes